version: "3.9"
services:
  api:
    build: ./dockerfiles/python
    depends_on:
      - db
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development

  redis:
    image: "redis:alpine"

  db:
    image: postgres:15.3
    container_name: postgres_15
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: $api_development

volumes:
  db-store:
