version: "3.9"
services:
  api:
    build: ./dockerfiles/python
    depends_on:
      - postgres
    volumes:
      - ./app:/app/
    command: >
      uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  unit_test:
    profiles:
      - testing
    build: ./dockerfiles/python
    depends_on:
      - postgres
    volumes:
      - ./app:/app/
    command: >
      python test_discover.py
    ports:
      - "8000:8000"

  postgres:
    image: postgres:15.3
    container_name: postgres_15
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: $api_development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-store:
