version: "3.9"
services:
  api:
    build: ./dockerfiles/python
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
